### ISSUE TITLE
multi-file uploader from web api

### ISSUE THREAD

**Issue by ht1080z** [estmob/SendAnywhere-Web-API#1]
Is there any ready made widget or example with other uploader js (like dropzonejs) to achieve multi-file upload with send-anywhere api?
Can I embed the main SendAnywhere upload widget (like in your website) into my project/web-app?

**Comment by sleephi** [comment]
Hi @ht1080z.

Unfortunately, there is no web widget api yet, however we'll support it early next year.
Please note that we've fixed html example to include multi-file usage. https://github.com/estmob/SendAnywhere-Web-API/commit/3e62a68a22ddd6c7a6605669d3955704f4c11434


Thanks!
