### ISSUE TITLE
The send.sh work strangely

### ISSUE THREAD

**Issue by mengyyy** [estmob/SendAnywhere-Web-API#2]
I get the api keys from [send-anywhere.com](https://send-anywhere.com/) 
When i try to send file us the [example send shell](https://github.com/estmob/SendAnywhere-Web-API/blob/master/example/shell/send.sh) ,it can get the key and file url, but the shell does not top.

root@xiaoming:~/SendAnywhere-Web-API/example/shell# ./send.sh  ./ddd.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198    0     0    0   198      0      0 --:--:--  0:04:32 --:--:--     0

100   198    0     0    0   198      0      0 --:--:--  0:04:34 --:--:--     0^C

**Comment by sleephi** [comment]
Hi @mengyyy 
send.sh is a script for direct transfer using 6 digit key. So it will wait until a peer receives the key.
It should print a key to console like this:
```
key: 123456
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   679    0    74  100   605      0      1  0:10:05  0:10:00  0:00:05     0
```
Enter the key into receiver's input box or excute ./receive.sh 123456 then the transfer will start.
Thanks.

**Comment by mengyyy** [comment]
```
import requests

API_KEY='123456789000000000000000000000000000'

auth_url = 'https://send-anywhere.com/web/v1/device?api_key={}&profile_name=Send%20Anywhere%20SDK'.format(API_KEY)
key_url = 'https://send-anywhere.com/web/v1/key'


def sendAnywhere(file):
    session = requests.Session()
    areq = session.get(auth_url)
    print(areq.content)
    kreq = session.get(key_url)
    print(kreq.content)
    key = kreq.json()['key']
    weblink = kreq.json()['weblink']
    files = {'file': open(file, 'rb')}
    preq = session.post(weblink, files=files)
    print(preq.content)


sendAnywhere('file_path')
```
